name: Build
on: 
  push:
    tags: [v*]
    branches: [main]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-package: 'jdk+fx'
          java-version: '8'
      - name: build
        run: |
          mkdir bin
          cd ${{github.workspace}}/source
          while read -r f; do
            javac -encoding SJIS "$f" -d ${{github.workspace}}/bin
          done < <(find . -mindepth 1 -maxdepth 1 -type f -name "*.java")
          cd ${{github.workspace}}
      - uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ${{github.workspace}}/bin
      - name: zip
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          tar czvf JavaPractice.tgz ${{github.workspace}}/bin
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{github.workspace}}/JavaPractice.tgz